export const AboutData = {
    Beef: "We custom feed beef cattle for investor clients as well as ourselves. By using progressive technology such as RFID tags and scales we are better able to monitor cattle performance and rate of gain. We partner with Performance Beef to record animal health and costs so investors can access information in real time. Being located in the center of the corn belt gives us an upperhand in keeping cost of gain low and allows us to capitalize on cheap byproducts from local ethanol plants and other corn processors.",
    Grain: "Peterson-Daly Farms currently farms corn, soybeans, hay, rye, and wheat. By using sustainable practices such as double-cropping, no-tilling, and more, Peterson-Daly Farms is proud to practice environmentally safe farming.",
    name1: "David",
    name2: "Daniel",
    para1: "After high school, David earned a degree at Universal Technical Institute. He would work at Illinois Material Handling as a Forklift Technician from 1993 to 2009, developing skills in repairs that would (unfortunately) be frequented on the farm to repair broken equipment. Helping father in-law Kent Peterson on the farm re-ignited a passion for farm work that hasn’t subsided since. Starting in 1998, David became a full-time farmer and Co-Manager of Peterson-Daly Farms in 2011. When Kent decided he was ready to pass the torch in 2020, David and wife Carrie became Co-Owners of Peterson-Daly Farms, determined to continue and improve on tradition. David has also served on the Pearl City Elevator’s Board of Directors since 2011.",
    para2: "Growing up on the farm, Daniel always knew he wanted to follow in the footsteps of his predecessors. Although he was eager to begin farming, he decided to attend Kirkwood Community College in Cedar Rapids, Iowa, to obtain a degree in Ag Business. Upon graduating, Daniel partnered with Burrus Seed, where he acquired a seed dealership. Wanting to continue the family tradition, he continues to work at Peterson-Daly farms, set on building something he and future Dalys can be proud of."
}
export const AboutMast = {
    title: "About Us"
}